services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: ecom_bot:dev
    container_name: ecom_bot
    ports:
      - "14007:14007"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped
 